apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: enr
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    nodePort: 30999
    protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: NodePort
